# Site Settings
#==================================
title: Free Rasmea!
email: freerasmea@riseup.net
description: Justice for Palestine Activist Rasmea Odeh
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
#==================================
markdown: redcarpet
redcarpet: 
  extensions: ["smart", "strikethrough"]

highlighter: pygments
exclude: [Gemfile, Gemfile.lock, readme.md]

# Permalinks
#==================================
permalink: pretty

# Assets
#==================================
sass:
  sass_dir: assets/styles/_scss  # default is _sass
  style: compressed # set to compressed for production


# Front-matter Defaults
#==================================
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

# Prose Settings
#==================================
prose:
  ignore: ['.gitignore', '_config.yml', 'test.html', 'Gemfile', 'Gemfile.lock', 'assets', '_includes', '_layouts', '_data']



